### ISSUE TITLE
About the prec1. 

### ISSUE THREAD

**Issue by wdmwhh** [jiweibo/ImageNet#4]
I clone the project and reexecute it with resnet50. However, it comes out only Prec@1 72.780 Prec@5 90.880. I only add "nn.DataParallel". Could you give me the final *.pth of resnet50？

Yours,
 Sincerely.

**Comment by jiweibo** [comment]
Sorry, i did not test results on multi-card.

please refer to  [torch resnet model](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L14)
