### ISSUE TITLE
ImageNet训练收敛问题

### ISSUE THREAD

**Issue by Linxu59** [jiweibo/ImageNet#5]
显卡内存不够，batchsize设置为200，前几个epoch TOP1和TOP5的准确率非常低，4个eopchs下来在验证集上TOP5只有0.005，是ImageNet数据集没弄好吗？还是本来就是这样呢？

**Comment by jiweibo** [comment]
0.005代表几乎没有学到任何东西，建议训练一晚上后再来看 val 的top5
